
project_id = "rigurrwjiaucodxuuzeh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev", "https://gptengineer.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true

[auth.external.github]
enabled = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions]
enabled = true
verify_jwt = true

[functions.handle-flask-sms-callback]
verify_jwt = false

[functions.send-sms-flask]
verify_jwt = true

[functions.process-invitation]
verify_jwt = false

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
