
project_id = "rigurrwjiaucodxuuzeh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.enhanced-invite-user]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = false
